version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-211-210-149.compute-1.amazonaws.com
            database: d1qnpuhcna1ab2
            # schema: public
            user: qszmiunjeahyjb
            password: 3e8ccaffa83ef40f3c9b5d2050b92c2bf6c9fefe90fb077fa8834a62d91490f4
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true 