version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-18-210-214-86.compute-1.amazonaws.com
            database: danvcuvs9cp4o3
            # schema: public
            user: mkymqbokkytcie
            password: fb39cdd50a03aa9aefcb4c1a2ad211c0ba83a3824f8ea6e293b9e17bb81ce773
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true 